name: Download B1ackDaemon RPCS3

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo only
        run: |
          git clone --depth 1 https://github.com/B1ackDaemon/rpcs3.git
          tar -czf rpcs3-source.tar.gz rpcs3

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rpcs3-source
          path: rpcs3-source.tar.gz
